"""
Hardware constants and channel definitions for the ephys acquisition system.

All other modules import from here.  This module is the **single authoritative
reference** for physical units, scaling factors, and hardware identifiers.

Overview for lab members
------------------------
This system records electrical signals from neurons using a patch-clamp amplifier
connected to a National Instruments PCIe-6323 data acquisition card (DAQ).
The DAQ digitises up to 5 analog input (AI) channels at 20 kHz and can also
output analog commands (AO) to the amplifier.

A camera is triggered via a transistor-transistor logic (TTL) square-wave pulse
train generated by a hardware counter on the DAQ card.

Physical units used throughout the codebase
--------------------------------------------
- **pA** (picoamperes): current — typical current-clamp injection values are
  in the range −500 to +1000 pA.
- **mV** (millivolts): voltage — membrane potentials typically −90 to +40 mV.
- **V** (Volts): raw DAQ voltage on the analog channels (−10 to +10 V range).
- **Hz**: sampling rate or camera frame rate.
- **ms**: stimulus timing (step widths, gaps, inter-trial intervals).

Amplifier command scaling
--------------------------
The amplifier's command input converts a voltage from the DAQ into a current
(current-clamp, CC) or a voltage offset (voltage-clamp, VC):

- **Current clamp**: amplifier command sensitivity = 400 pA per Volt (AO_PA_PER_VOLT).
  To inject *X* pA, write *X / 400* V to ao0.
  Example: 200 pA → 0.5 V on ao0.

- **Voltage clamp**: amplifier command sensitivity = 20 mV per Volt (AO_MV_PER_VOLT).
  To step the holding potential by *X* mV, write *X / 20* V to ao0.
  Example: −40 mV step → −2.0 V on ao0.

Analog input scaling
--------------------
Raw DAQ voltages (V) are multiplied by ``display_scale`` to obtain display
units.  Each channel entry in :data:`AI_CHANNELS` carries its own scale:

===========  ====================  =====================================
Channel      Raw → Display         Physical meaning
===========  ====================  =====================================
ScAmpOut     V × 10.0 → mV        Scaled amplifier output (membrane V)
RawAmpOut    V × 2.0  → nA        Raw current monitor
AmpCmd       V × 400  → pA        Amplifier command signal (loopback)
Camera       V × 1.0  → V         Camera TTL loopback / sync pulse
TTLLoopback  V × 1.0  → V         DAQ TTL output loopback
===========  ====================  =====================================

Developer notes
---------------
- The ``ChannelDef`` type alias describes the 5-tuple format used in
  :data:`AI_CHANNELS` and :data:`AI_CHANNELS_VC`.
- Constants in this module are intentionally module-level (not dataclass fields)
  so they are importable as plain names without instantiating anything.
"""

from __future__ import annotations

from typing import TypeAlias

# ---------------------------------------------------------------------------
# Type alias for channel definition tuples
# ---------------------------------------------------------------------------

ChannelDef: TypeAlias = tuple[str, str, str, float, str]
"""A 5-tuple describing one analog input channel.

Fields:
    display_name (str):   Human-readable label shown in the trace panel.
    ni_channel (str):     NI channel string, e.g. ``"ai0"``.
    terminal_config (str): ``"differential"`` or ``"rse"``.
    display_scale (float): Multiply raw Volts by this to get display units.
    units (str):           Display unit label, e.g. ``"mV"``, ``"pA"``.
"""

# ---------------------------------------------------------------------------
# NI DAQ device
# ---------------------------------------------------------------------------

DEVICE_NAME: str = "Dev1"
"""NI DAQ device name as shown in NI MAX (Measurement & Automation Explorer)."""

# ---------------------------------------------------------------------------
# Acquisition timing
# ---------------------------------------------------------------------------

SAMPLE_RATE: int = 20000
"""AI/AO sample rate in Hz.  The 20 kHz rate gives 50 µs temporal resolution,
sufficient to resolve action potentials (~1 ms width)."""

CHUNK_SIZE: int = 200
"""Number of samples read from the AI task per loop iteration.

At 20 kHz this equals ~10 ms of data per chunk, giving the GUI thread a
callback rate of ~100 Hz — fast enough for live display without excessive
CPU overhead.
"""

DISPLAY_SECONDS: int = 5
"""Duration of the rolling window shown in the live trace panel (seconds)."""

DISPLAY_SAMPLES: int = SAMPLE_RATE * DISPLAY_SECONDS
"""Total samples held in the ring buffer (``SAMPLE_RATE × DISPLAY_SECONDS``)."""

# ---------------------------------------------------------------------------
# Analog input channels — current-clamp (CC) mode
# ---------------------------------------------------------------------------

AI_CHANNELS: list[ChannelDef] = [
    ("ScAmpOut",    "ai0", "differential", 10.0,  "mV"),
    ("RawAmpOut",   "ai1", "differential",  2.0,  "nA"),
    ("AmpCmd",      "ai2", "differential", 400.0, "pA"),
    ("Camera",      "ai3", "rse",           1.0,  "V"),
    ("TTLLoopback", "ai4", "differential",  1.0,  "V"),
]
"""Analog input channel definitions for current-clamp (CC) mode.

Each entry is a :data:`ChannelDef` tuple:
``(display_name, ni_channel, terminal_config, display_scale, units)``.

The channel order here determines the row order of all data arrays throughout
the codebase (row 0 = ScAmpOut, row 4 = TTLLoopback).

Scaling:
    - ai0 (ScAmpOut):    0.1 V/mV amplifier gain → display_scale = 10.0 mV/V
    - ai1 (RawAmpOut):   0.5 V/nA amplifier gain → display_scale = 2.0 nA/V
    - ai2 (AmpCmd):      400 pA/V command sens.  → display_scale = 400.0 pA/V
    - ai3 (Camera):      direct TTL readback      → display_scale = 1.0 V/V
    - ai4 (TTLLoopback): direct TTL readback      → display_scale = 1.0 V/V
"""

N_AI_CHANNELS: int = len(AI_CHANNELS)
"""Number of analog input channels (5)."""

# ---------------------------------------------------------------------------
# Analog input channels — voltage-clamp (VC) mode
# ---------------------------------------------------------------------------

AI_CHANNELS_VC: list[ChannelDef] = [
    ("I_mem",       "ai0", "differential", 0.1,    "nA"),
    ("V_pip",       "ai1", "differential", 1000.0, "mV"),
    ("AmpCmd",      "ai2", "differential", 400.0,  "pA"),
    ("Camera",      "ai3", "rse",          1.0,    "V"),
    ("TTLLoopback", "ai4", "differential", 1.0,    "V"),
]
"""Analog input channel definitions for voltage-clamp (VC) mode.

The physical channels are the same (ai0–ai4), but the amplifier output
interpretation changes:

- ai0 (I_mem):   10 V/nA amplifier gain  → display_scale = 0.1 nA/V
- ai1 (V_pip):   1 V/V  pipette voltage  → display_scale = 1000.0 mV/V
- ai2–ai4: identical to :data:`AI_CHANNELS`.
"""

# ---------------------------------------------------------------------------
# Analog output
# ---------------------------------------------------------------------------

AO_COMMAND_CH: str = "ao0"
"""NI analog output channel used for amplifier command current/voltage."""

AO_PA_PER_VOLT: float = 400.0
"""Amplifier command sensitivity in current-clamp mode: 400 pA per Volt.

To inject *X* pA: write ``X / AO_PA_PER_VOLT`` Volts to ao0.
"""

AO_MV_PER_VOLT: float = 20.0
"""Amplifier command sensitivity in voltage-clamp mode: 20 mV per Volt.

To step the holding potential by *X* mV: write ``X / AO_MV_PER_VOLT`` Volts to ao0.
This value matches the Axopatch 200B VC external command sensitivity.
Override via ``TrialProtocol.ao_mv_per_volt`` for other amplifiers.
"""

# ---------------------------------------------------------------------------
# Counter / TTL output for camera triggering
# ---------------------------------------------------------------------------

CTR_CHANNEL: str = "ctr0"
"""NI counter channel used to generate the camera TTL pulse train."""

CTR_OUT_TERMINAL: str = "PFI12"
"""Physical output terminal for CTR0 on the PCIe-6323 (default mapping).

Connect this BNC/pin to the camera's external trigger input.
"""

TTL_HIGH_V: float = 5.0
"""TTL logic-high voltage in Volts (camera trigger active state)."""

TTL_LOW_V: float = 0.0
"""TTL logic-low voltage in Volts (camera trigger inactive state)."""

DEFAULT_FRAME_RATE_HZ: float = 100.0
"""Default camera frame rate in Hz.

100 Hz divides evenly into 20 kHz (period = 200 samples), so no integer
rounding error occurs at the default setting.
"""

DEFAULT_EXPOSURE_MS: float = 5.0
"""Default camera exposure duration in ms.

Must be less than the TTL period (1000 / frame_rate_hz ms) to avoid
overlap between consecutive trigger pulses.
"""

CAMERA_GUARD_DELAY_MS: int = 2000
"""Guard delay in ms applied after stopping the camera TTL.

After ``stop_ttl()`` is called, the HDF5 file remains open for this
duration so that any trailing exposure-signal transients on ai3 (Camera)
are captured before the file is closed.
"""

# ---------------------------------------------------------------------------
# Display defaults
# ---------------------------------------------------------------------------

AI_Y_DEFAULTS: list[tuple[float, float]] = [
    (-100.0,  100.0),   # ScAmpOut  (mV)
    ( -10.0,   10.0),   # RawAmpOut (nA)
    (-500.0,  500.0),   # AmpCmd    (pA)
    (  -0.5,    5.5),   # Camera    (V)
    (  -0.5,    5.5),   # TTLLoopback (V)
]
"""Default Y-axis (min, max) ranges in display units for each AI channel.

Indices correspond to :data:`AI_CHANNELS` row order.
"""

TRACE_COLORS: list[str] = [
    "#00BFFF",   # ScAmpOut    — sky blue
    "#FF6B6B",   # RawAmpOut   — coral
    "#98FF98",   # AmpCmd      — mint green
    "#FFD700",   # Camera      — gold
    "#DA70D6",   # TTLLoopback — orchid
]
"""Hex color strings for each channel's trace in the live display.

Indices correspond to :data:`AI_CHANNELS` row order.
"""
