"""
DAQWorker — QThread that runs continuous AI acquisition and AO output.

Lifecycle::

    worker = DAQWorker(frame_rate_hz, exposure_ms)
    worker.data_ready.connect(some_slot)
    worker.start()          # launches run() in a new thread
    ...
    worker.stop()
    worker.wait()

Thread safety
-------------
``data_ready`` is emitted from the worker thread.  Qt ``AutoConnection``
(the default) queues the signal for delivery in the receiver's thread.
**Do not** change to ``DirectConnection`` or the slot will execute on the
worker thread, potentially causing data races with GUI state.

Pending-update protocol
-----------------------
Methods called from the GUI thread (``set_stimulus_waveform``,
``start_ttl``, etc.) do not communicate with the hardware directly.
Instead, they write sentinel values into ``_pending_*`` attributes
protected by ``_lock`` (a ``threading.Lock``).  At the top of each
loop iteration the worker thread drains these pending values atomically
and processes them.  Three sentinel objects distinguish the states:

- ``_NO_CHANGE``: no pending waveform update (waveform field default).
- ``_CLEAR``: revert ao0 to zeros.
- A numpy array ``(1, N)``: install this as the new AO waveform.

nidaqmx availability
--------------------
``HAS_NIDAQMX`` is set to ``True`` only when nidaqmx can be imported.
On machines without the NI driver the worker emits an ``error_occurred``
signal immediately from ``run()`` and returns, so the rest of the
application can remain functional for UI development and testing.
"""

from __future__ import annotations

import threading

import numpy as np
from numpy.typing import NDArray

from PySide6.QtCore import QThread, Signal

from config import CHUNK_SIZE, N_AI_CHANNELS, SAMPLE_RATE, DEFAULT_FRAME_RATE_HZ, DEFAULT_EXPOSURE_MS

try:
    from hardware.daq_config import (
        HAS_NIDAQMX,
        build_ai_task,
        build_ao_task,
        build_ttl_counter_task,
        make_reader,
        make_writer,
    )
    import nidaqmx.errors
except ImportError:
    HAS_NIDAQMX = False


_NO_CHANGE = object()   # sentinel: no pending waveform update
_CLEAR     = object()   # sentinel: revert ao0 to zeros
_TTL_START = object()   # sentinel: start the counter TTL output
_TTL_STOP  = object()   # sentinel: stop the counter TTL output


class DAQWorker(QThread):
    """Continuously reads AI and writes AO on a NI PCIe-6323.

    Camera TTL is generated by a dedicated counter task (CTR0 → PFI12)
    that runs independently of the AO task, so stimulus waveform changes
    never disrupt the trigger timing.

    Signals:
        data_ready(object): Emitted from the worker thread after each
            :data:`~config.CHUNK_SIZE`-sample read.  The argument is a
            ``numpy.ndarray`` of shape ``(N_AI_CHANNELS, CHUNK_SIZE)``
            in raw Volts.  Connect with ``AutoConnection`` (default) so
            the slot runs in the receiver's thread.
        error_occurred(str): Emitted with a human-readable message when
            the acquisition loop raises an unexpected exception.

    Attributes:
        _running (bool): Loop-exit flag.  Set to ``False`` by :meth:`stop`.
        _frame_rate (float): Current counter frame rate in Hz.
        _exposure_ms (float): Current camera exposure in ms.
        _lock (threading.Lock): Guards all ``_pending_*`` attributes.
        _pending_waveform: ``_NO_CHANGE``, ``_CLEAR``, or a ``(1, N)``
            float64 array to install as the new AO waveform.
        _pending_ttl_cfg: ``None`` or a ``(frame_rate, exposure_ms)``
            tuple requesting a counter task rebuild.
        _pending_ttl_action: ``None``, ``_TTL_START``, or ``_TTL_STOP``.
    """

    data_ready     = Signal(object)   # np.ndarray shape (N_AI_CHANNELS, CHUNK_SIZE)
    error_occurred = Signal(str)

    def __init__(
        self,
        frame_rate_hz: float = DEFAULT_FRAME_RATE_HZ,
        exposure_ms:   float = DEFAULT_EXPOSURE_MS,
        parent=None,
    ) -> None:
        """Initialise the worker with TTL settings.

        Args:
            frame_rate_hz: Initial camera frame rate in Hz.
            exposure_ms: Initial camera exposure duration in ms.
            parent: Optional Qt parent object.
        """
        super().__init__(parent)
        self._running       = False
        self._frame_rate    = frame_rate_hz
        self._exposure_ms   = exposure_ms

        # Pending updates (set from GUI thread, consumed in worker thread)
        self._lock:               threading.Lock = threading.Lock()
        self._pending_waveform                   = _NO_CHANGE
        self._pending_ttl_cfg:    tuple | None   = None
        self._pending_ttl_action                 = None

    # ------------------------------------------------------------------
    # Public slots / methods (called from GUI thread)
    # ------------------------------------------------------------------

    def stop(self) -> None:
        """Signal the worker thread to exit the acquisition loop.

        The thread completes the current chunk read before exiting.
        Call :meth:`wait` (or ``wait(ms)``) afterwards to block until
        the thread has fully shut down.
        """
        self._running = False

    def set_stimulus_waveform(self, ao0_1xN: NDArray[np.float64]) -> None:
        """Schedule a new ao0 command-current waveform for the next loop iteration.

        The waveform is applied at the start of the next acquisition loop
        cycle by rebuilding the AO task.  The camera TTL (counter task) is
        unaffected.

        Args:
            ao0_1xN: 2-D float64 array of shape ``(1, N)`` in Volts.  The
                ``N`` dimension sets the waveform length; the board loops
                it continuously via ``ALLOW_REGENERATION``.  Convert pA to
                Volts using :data:`~config.AO_PA_PER_VOLT` before calling.

        Note:
            Thread-safe: uses ``_lock`` internally.
        """
        with self._lock:
            self._pending_waveform = ao0_1xN.copy()

    def clear_stimulus_waveform(self) -> None:
        """Schedule ao0 to revert to zero (silent) at the next loop iteration.

        The TTL counter is unaffected.

        Note:
            Thread-safe: uses ``_lock`` internally.
        """
        with self._lock:
            self._pending_waveform = _CLEAR

    def start_ttl(self) -> None:
        """Schedule the counter TTL output to start at the next loop iteration.

        The camera will begin receiving trigger pulses at ``frame_rate_hz``.

        Note:
            Thread-safe: uses ``_lock`` internally.
        """
        with self._lock:
            self._pending_ttl_action = _TTL_START

    def stop_ttl(self) -> None:
        """Schedule the counter TTL output to stop at the next loop iteration.

        The camera will stop receiving trigger pulses after the current
        period completes.

        Note:
            Thread-safe: uses ``_lock`` internally.
        """
        with self._lock:
            self._pending_ttl_action = _TTL_STOP

    def set_ttl_config(self, frame_rate_hz: float, exposure_ms: float) -> None:
        """Schedule a TTL parameter update for the next loop iteration.

        The counter task is rebuilt with the new parameters.  If the TTL
        was active it is automatically restarted at the new rate.

        Args:
            frame_rate_hz: New camera frame rate in Hz.
            exposure_ms: New camera exposure duration in ms.

        Note:
            Thread-safe: uses ``_lock`` internally.
        """
        with self._lock:
            self._pending_ttl_cfg = (frame_rate_hz, exposure_ms)

    # ------------------------------------------------------------------
    # QThread.run — helpers (execute in the worker thread)
    # ------------------------------------------------------------------

    def _samples_per_frame(self) -> int:
        """Number of AO samples in one camera-frame period."""
        return max(1, int(SAMPLE_RATE / self._frame_rate))

    def _drain_pending(self) -> tuple:
        """Snapshot and reset all pending GUI-thread requests under ``_lock``.

        Returns:
            A 3-tuple ``(pending_wf, pending_ttl, pending_ttl_action)``.
        """
        with self._lock:
            pending_wf         = self._pending_waveform
            pending_ttl        = self._pending_ttl_cfg
            pending_ttl_action = self._pending_ttl_action
            self._pending_waveform   = _NO_CHANGE
            self._pending_ttl_cfg    = None
            self._pending_ttl_action = None
        return pending_wf, pending_ttl, pending_ttl_action

    def _handle_ttl(self, ctr_task, pending_ttl_action, pending_ttl,
                    ttl_active: bool) -> tuple:
        """Process TTL start/stop and reconfiguration requests.

        Args:
            ctr_task: Current counter task (may be rebuilt).
            pending_ttl_action: ``_TTL_START``, ``_TTL_STOP``, or ``None``.
            pending_ttl: ``(frame_rate, exposure_ms)`` tuple or ``None``.
            ttl_active: Whether the counter is currently running.

        Returns:
            A 2-tuple ``(ctr_task, ttl_active)`` — the (possibly new)
            counter task and updated active flag.
        """
        if pending_ttl_action is _TTL_START:
            ctr_task.start()
            ttl_active = True
        elif pending_ttl_action is _TTL_STOP:
            ctr_task.stop()
            ttl_active = False

        if pending_ttl is not None:
            self._frame_rate  = pending_ttl[0]
            self._exposure_ms = pending_ttl[1]
            try:
                ctr_task.stop()
                ctr_task.close()
            except Exception:
                pass
            ctr_task = build_ttl_counter_task(self._frame_rate, self._exposure_ms)
            if ttl_active:
                ctr_task.start()

        return ctr_task, ttl_active

    def _handle_ao(self, ao_task, writer, pending_wf) -> tuple:
        """Process AO waveform update requests.

        Args:
            ao_task: Current AO task (may be rebuilt).
            writer: Current AO writer (may be replaced).
            pending_wf: ``_NO_CHANGE``, ``_CLEAR``, or a ``(1, N)`` array.

        Returns:
            A 2-tuple ``(ao_task, writer)`` — the (possibly new) AO task
            and writer.
        """
        if pending_wf is _CLEAR:
            n_zero = self._samples_per_frame()
            ao_task, writer = self._rebuild_ao(
                ao_task, np.zeros((1, n_zero), dtype=np.float64))
        elif pending_wf is not _NO_CHANGE:
            ao_task, writer = self._rebuild_ao(ao_task, pending_wf)
        return ao_task, writer

    @staticmethod
    def _rebuild_ao(
        old_ao_task,
        new_wf: NDArray[np.float64],
    ) -> tuple:
        """Stop the old AO task, build a new one sized for ``new_wf``, and start it.

        Rebuilding is necessary because the nidaqmx buffer size is fixed at
        task creation time; changing the waveform length requires a new task.

        Args:
            old_ao_task: The existing ``nidaqmx.Task`` to close, or ``None``.
            new_wf: New waveform array of shape ``(1, N)`` in Volts.

        Returns:
            A 2-tuple ``(new_ao_task, new_writer)`` — the freshly started
            task and its associated writer.
        """
        if old_ao_task is not None:
            try:
                old_ao_task.stop()
                old_ao_task.close()
            except Exception:
                pass

        n_wf = new_wf.shape[1]
        new_ao_task = build_ao_task(n_wf)
        new_ao_task.out_stream.auto_start = False
        new_writer = make_writer(new_ao_task)
        new_writer.write_many_sample(new_wf)
        new_ao_task.start()
        return new_ao_task, new_writer

    def run(self) -> None:
        """Acquisition loop — runs in the worker thread until :meth:`stop` is called.

        Start-up sequence:

        1. Build AI, AO, and CTR tasks.
        2. Pre-load a zero waveform to AO.
        3. Start AO first (waits for the AI clock edge).
        4. Start AI (clock master — triggers the first AO sample).
        5. Enter the main loop.

        Main loop (each iteration ≈ 10 ms at 20 kHz / 200-sample chunks):

        1. Atomically drain all pending GUI-thread requests under ``_lock``.
        2. Handle TTL start / stop (counter task).
        3. Rebuild counter if parameters changed (``_pending_ttl_cfg``).
        4. Rebuild AO task if waveform changed (``_pending_waveform``).
        5. Read :data:`~config.CHUNK_SIZE` samples from AI into ``ai_buf``.
        6. Emit ``data_ready`` with a copy of ``ai_buf``.

        Shutdown (``finally`` block — runs even on exception):

        Stop CTR → AO → AI in that order (reverse of start order).
        Exceptions during shutdown are silently suppressed.

        Note:
            If nidaqmx is not installed, emits ``error_occurred`` immediately
            and returns without entering the loop.
        """
        if not HAS_NIDAQMX:
            self.error_occurred.emit(
                "nidaqmx not installed. Install it with: pip install nidaqmx"
            )
            return

        self._running = True
        ai_task = ao_task = ctr_task = None

        try:
            n_wf       = self._samples_per_frame()
            initial_wf = np.zeros((1, n_wf), dtype=np.float64)

            ai_task  = build_ai_task()
            ao_task  = build_ao_task(n_wf)
            ao_task.out_stream.auto_start = False
            ctr_task = build_ttl_counter_task(self._frame_rate, self._exposure_ms)

            writer = make_writer(ao_task)
            writer.write_many_sample(initial_wf)

            reader = make_reader(ai_task)
            ai_buf = np.zeros((N_AI_CHANNELS, CHUNK_SIZE), dtype=np.float64)

            # AO must start before AI (AO waits for AI clock).
            # Counter uses its own 100 MHz timebase and is started on demand.
            ao_task.start()
            ai_task.start()

            ttl_active = False

            while self._running:
                pending_wf, pending_ttl, pending_ttl_action = self._drain_pending()
                ctr_task, ttl_active = self._handle_ttl(
                    ctr_task, pending_ttl_action, pending_ttl, ttl_active)
                ao_task, writer = self._handle_ao(ao_task, writer, pending_wf)

                reader.read_many_sample(ai_buf, CHUNK_SIZE, timeout=2.0)
                self.data_ready.emit(ai_buf.copy())

        except Exception as exc:
            if self._running:   # suppress errors during intentional shutdown
                self.error_occurred.emit(str(exc))
        finally:
            # Stop counter first (independent), then AO (slave), then AI (clock master)
            for task in (ctr_task, ao_task, ai_task):
                if task is not None:
                    try:
                        task.stop()
                        task.close()
                    except Exception:
                        pass
            self._running = False
