"""
DAQWorker — QThread that runs continuous AI acquisition and AO output.

Lifecycle:
    worker = DAQWorker(frame_rate_hz, exposure_ms)
    worker.data_ready.connect(some_slot)
    worker.start()          # launches run() in a new thread
    ...
    worker.stop()
    worker.wait()

Thread safety:
    data_ready is emitted from the worker thread.  Qt AutoConnection
    (the default) queues the signal for delivery in the receiver's
    thread — do NOT change to DirectConnection or you will get races.
"""

import threading
import numpy as np

from PySide6.QtCore import QThread, Signal

from config import CHUNK_SIZE, N_AI_CHANNELS, SAMPLE_RATE, DEFAULT_FRAME_RATE_HZ, DEFAULT_EXPOSURE_MS

try:
    from hardware.daq_config import (
        HAS_NIDAQMX,
        build_ai_task,
        build_ao_task,
        build_ttl_counter_task,
        make_reader,
        make_writer,
    )
    import nidaqmx.errors
except ImportError:
    HAS_NIDAQMX = False


_NO_CHANGE = object()   # sentinel: no pending waveform update
_CLEAR     = object()   # sentinel: revert ao0 to zeros
_TTL_START = object()   # sentinel: start the counter TTL output
_TTL_STOP  = object()   # sentinel: stop the counter TTL output


class DAQWorker(QThread):
    """
    Continuously reads AI and writes AO on a NI PCIe-6323.

    Camera TTL is generated by a dedicated counter task (CTR0 → PFI12)
    that runs independently of the AO task, so stimulus waveform changes
    never disrupt the trigger timing.

    Signals:
        data_ready(np.ndarray): shape (N_AI_CHANNELS, CHUNK_SIZE) raw Volts
        error_occurred(str):    human-readable error message
    """

    data_ready     = Signal(object)   # np.ndarray
    error_occurred = Signal(str)

    def __init__(
        self,
        frame_rate_hz: float = DEFAULT_FRAME_RATE_HZ,
        exposure_ms:   float = DEFAULT_EXPOSURE_MS,
        parent=None,
    ):
        super().__init__(parent)
        self._running       = False
        self._frame_rate    = frame_rate_hz
        self._exposure_ms   = exposure_ms

        # Pending updates (set from GUI thread, consumed in worker thread)
        self._lock               = threading.Lock()
        self._pending_waveform   = _NO_CHANGE   # (1, N) float64, _CLEAR, or _NO_CHANGE
        self._pending_ttl_cfg    = None          # (frame_rate, exposure_ms) tuple or None
        self._pending_ttl_action = None          # _TTL_START, _TTL_STOP, or None

    # ------------------------------------------------------------------
    # Public slots / methods (called from GUI thread)
    # ------------------------------------------------------------------

    def stop(self) -> None:
        self._running = False

    def set_stimulus_waveform(self, ao0_1xN: np.ndarray) -> None:
        """
        Schedule a new ao0 command-current waveform (shape 1×N, Volts).
        Applied at the next loop iteration.  TTL is unaffected.
        """
        with self._lock:
            self._pending_waveform = ao0_1xN.copy()

    def clear_stimulus_waveform(self) -> None:
        """Revert ao0 to zero.  TTL is unaffected."""
        with self._lock:
            self._pending_waveform = _CLEAR

    def start_ttl(self) -> None:
        """Start the counter TTL output (camera triggers begin)."""
        with self._lock:
            self._pending_ttl_action = _TTL_START

    def stop_ttl(self) -> None:
        """Stop the counter TTL output (camera triggers cease)."""
        with self._lock:
            self._pending_ttl_action = _TTL_STOP

    def set_ttl_config(self, frame_rate_hz: float, exposure_ms: float) -> None:
        """
        Update TTL parameters.  The counter task is rebuilt at the next
        loop iteration; if TTL was running it is restarted automatically.
        """
        with self._lock:
            self._pending_ttl_cfg = (frame_rate_hz, exposure_ms)

    # ------------------------------------------------------------------
    # QThread.run — executes in the worker thread
    # ------------------------------------------------------------------

    @staticmethod
    def _rebuild_ao(old_ao_task, new_wf: np.ndarray):
        """
        Stop and destroy the old AO task, build a new one sized for
        *new_wf* (shape 1×N for ao0 only), write the waveform, and
        start the new task.

        Returns (new_ao_task, new_writer).
        """
        if old_ao_task is not None:
            try:
                old_ao_task.stop()
                old_ao_task.close()
            except Exception:
                pass

        n_wf = new_wf.shape[1]
        new_ao_task = build_ao_task(n_wf)
        new_ao_task.out_stream.auto_start = False
        new_writer = make_writer(new_ao_task)
        new_writer.write_many_sample(new_wf)
        new_ao_task.start()
        return new_ao_task, new_writer

    def run(self) -> None:
        if not HAS_NIDAQMX:
            self.error_occurred.emit(
                "nidaqmx not installed. Install it with: pip install nidaqmx"
            )
            return

        self._running = True
        ai_task = ao_task = ctr_task = None

        try:
            n_wf       = max(1, int(SAMPLE_RATE / self._frame_rate))
            initial_wf = np.zeros((1, n_wf), dtype=np.float64)

            ai_task  = build_ai_task()
            ao_task  = build_ao_task(n_wf)
            ao_task.out_stream.auto_start = False
            ctr_task = build_ttl_counter_task(self._frame_rate, self._exposure_ms)

            writer = make_writer(ao_task)
            writer.write_many_sample(initial_wf)

            reader = make_reader(ai_task)
            ai_buf = np.zeros((N_AI_CHANNELS, CHUNK_SIZE), dtype=np.float64)

            # AO must start before AI (AO waits for AI clock).
            # Counter uses its own 100 MHz timebase and is started on demand.
            ao_task.start()
            ai_task.start()

            ttl_active = False

            while self._running:
                # -- Collect pending changes from GUI thread --
                pending_wf         = _NO_CHANGE
                pending_ttl        = None
                pending_ttl_action = None
                with self._lock:
                    pending_wf         = self._pending_waveform
                    pending_ttl        = self._pending_ttl_cfg
                    pending_ttl_action = self._pending_ttl_action
                    self._pending_waveform   = _NO_CHANGE
                    self._pending_ttl_cfg    = None
                    self._pending_ttl_action = None

                # -- TTL counter: start / stop --
                if pending_ttl_action is _TTL_START:
                    ctr_task.start()
                    ttl_active = True
                elif pending_ttl_action is _TTL_STOP:
                    ctr_task.stop()
                    ttl_active = False

                # -- TTL reconfiguration: rebuild counter with new params --
                if pending_ttl is not None:
                    self._frame_rate  = pending_ttl[0]
                    self._exposure_ms = pending_ttl[1]
                    try:
                        ctr_task.stop()
                        ctr_task.close()
                    except Exception:
                        pass
                    ctr_task = build_ttl_counter_task(self._frame_rate, self._exposure_ms)
                    if ttl_active:
                        ctr_task.start()

                # -- AO command waveform updates --
                if pending_wf is _CLEAR:
                    n_zero = max(1, int(SAMPLE_RATE / self._frame_rate))
                    ao_task, writer = self._rebuild_ao(
                        ao_task, np.zeros((1, n_zero), dtype=np.float64))

                elif pending_wf is not _NO_CHANGE:
                    # New stimulus waveform (ao0 only, shape 1×N)
                    ao_task, writer = self._rebuild_ao(ao_task, pending_wf)

                # -- Read AI --
                reader.read_many_sample(ai_buf, CHUNK_SIZE, timeout=2.0)
                self.data_ready.emit(ai_buf.copy())

        except Exception as exc:
            if self._running:   # suppress errors that occur during intentional shutdown
                self.error_occurred.emit(str(exc))
        finally:
            # Stop counter first (independent), then AO (slave), then AI (clock master)
            for task in (ctr_task, ao_task, ai_task):
                if task is not None:
                    try:
                        task.stop()
                        task.close()
                    except Exception:
                        pass
            self._running = False
